version: "3.8"

services:
  hermes:
    image: nousresearch/hermes-agent:latest
    container_name: hermes-gateway
    restart: unless-stopped
    # command: gateway run
    volumes:
      - hermes-data:/opt/data
    environment:
      - TZ=Africa/Lagos
      # - PATH=/opt/hermes/.venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

volumes:
  hermes-data:
